import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'PRISM Terms of Service — your rights and responsibilities when using PRISM.',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
      <div className="mb-10">
        <Link
          href="/"
          className="text-sm text-emerald-600 dark:text-emerald-400 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 rounded"
        >
          ← Back to PRISM
        </Link>
      </div>

      <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-slate-50 mb-3">
        Terms of Service
      </h1>
      <p className="text-sm text-slate-500 dark:text-slate-400 mb-10">
        Last updated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
      </p>

      <div className="space-y-8">

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            1. Acceptance of Terms
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            By creating an account or using PRISM, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, do not use PRISM. These terms constitute a legally binding agreement between you and Epopteia, the company that operates PRISM.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            2. Description of Service
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            PRISM is a document intelligence platform that allows users to upload PDF documents and query them using artificial intelligence. PRISM provides AI-generated answers with citations to source material. PRISM is a research and productivity tool — it is not a substitute for professional legal, financial, or other specialist advice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            3. Your Account
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorised use. You must be at least 18 years of age to use PRISM.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            4. Acceptable Use
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            You agree not to use PRISM to upload documents you do not have the right to process, to circumvent security measures, to attempt to access other users&apos; data, to reverse engineer the platform, or to use the service in any way that violates applicable law. You retain all rights to documents you upload — PRISM does not claim ownership of your content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            5. AI-Generated Content
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            PRISM uses artificial intelligence to generate answers from your documents. AI-generated content may be incomplete, inaccurate, or misleading. You are solely responsible for verifying any information generated by PRISM before relying on it for professional, legal, financial, or other consequential decisions. PRISM is a research tool, not legal advice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            6. Subscription and Billing
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            PRISM offers free and paid subscription tiers. Paid subscriptions are billed monthly via Paystack, a licensed payment processor regulated by the Central Bank of Nigeria. You may cancel at any time — cancellation takes effect at the end of the current billing period. We reserve the right to change pricing with 30 days&apos; notice to existing subscribers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            7. Data and Privacy
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            Your use of PRISM is also governed by our{' '}
            <Link href="/privacy" className="text-emerald-600 dark:text-emerald-400 hover:underline">
              Privacy Policy
            </Link>
            , which is incorporated into these Terms by reference. Your documents are never used to train any AI model.
          </p>
        </section>

        <section>
         <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
           8. Nigeria Data Protection Act 2023 Compliance
         </h2>
         <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
           PRISM processes personal data in accordance with the Nigeria Data Protection Act 2023 (NDPA) and the General Application and Implementation Directive issued by the Nigeria Data Protection Commission (NDPC). As a data controller, Epopteia collects only the minimum personal data necessary to provide the service, processes data on a lawful basis, and implements appropriate technical and organisational measures to protect personal data against unauthorised access, loss, or destruction. You have the right to access, rectify, and request erasure of your personal data at any time by contacting us at the address in Clause 14.
         </p>
       </section>       

       <section>
         <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
           9. Nigerian Bar Association AI Guidelines Compliance
         </h2>
         <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
          PRISM is designed and operated in accordance with the Nigerian Bar Association Guidelines for the Use of Artificial Intelligence in Legal Practice (September 2024). Specifically: PRISM maintains human oversight through its epistemic categorisation system, which classifies every answer as Explicitly Stated, Inferred, or Silent — ensuring lawyers verify AI outputs before reliance. PRISM maintains full transparency through its Glass Box citation architecture, which traces every answer to its exact source paragraph. PRISM never presents AI-generated content as legal advice. PRISM does not engage in any form of data mining or profiling of users.
          </p>
        </section>
        
        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            10. Professional Indemnity Position
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            PRISM is a research assistance tool. All outputs must be verified by a qualified legal professional before use in legal proceedings, client advice, or any other consequential application. Epopteia accepts no liability for reliance on unverified AI-generated outputs. The NBA Guidelines explicitly require human oversight of AI outputs in legal practice — PRISM&apos;s architecture is designed to support and enforce this requirement at every stage of the pipeline.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            11. Limitation of Liability
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            To the maximum extent permitted by law, Epopteia shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of PRISM. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            12. Termination
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            We reserve the right to suspend or terminate your account for violation of these terms. You may delete your account at any time from your Profile page. Upon deletion, all your data is permanently purged in accordance with our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            13. Changes to Terms
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            We may update these Terms from time to time. We will notify you of material changes by email or by a notice within PRISM. Continued use of the service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 dark:text-slate-50 mb-3">
            14. Contact
          </h2>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            For questions about these Terms, contact Epopteia at{' '}
            <a
              href="mailto:legal@epopteia.com"
              className="text-emerald-600 dark:text-emerald-400 hover:underline"
            >
              legal@epopteia.com
            </a>
          </p>
        </section>

      </div>

      <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-700 flex gap-6 text-sm">
        <Link href="/privacy" className="text-emerald-600 dark:text-emerald-400 hover:underline">
          Privacy Policy →
        </Link>
        <Link href="/" className="text-slate-500 dark:text-slate-400 hover:underline">
          Back to PRISM
        </Link>
      </div>
    </div>
  )
}